---
name: "CI"

on: [push, pull_request]

jobs:
    ci:
        runs-on: "ubuntu-latest"

        steps:
        
            - name: Checkout Source
              uses: actions/checkout@v4

            - name: Build
              run:  "make clean && make"
